version: '2'
services:
    rfb-app:
        image: rfb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rfb-mysql:3306/rfb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=rfb-elasticsearch:9300
        ports:
            - 8080:8080
    rfb-mysql:
        extends:
            file: mysql.yml
            service: rfb-mysql
    rfb-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: rfb-elasticsearch
